# Hugo Blox GitHub Action to convert Bibtex publications to Markdown-based webpages
name: Import Publications From Bibtex

# Require permission to create a PR
permissions:
  contents: write
  pull-requests: write

# Run workflow when a `.bib` file is added or updated in the `data/` folder
on:
  push:
    branches: ['main']
    paths: ['publications.bib']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugoblox:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout the repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Python 3.12
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install academic==0.10.0
      - name: Run Academic (Bibtex To Markdown Converter)
        # Check `.bib` file exists for case when action runs on `.bib` deletion
        # Note GH only provides hashFiles func in `steps.if` context, not `jobs.if` context
        if: ${{ hashFiles('publications.bib') != '' }}
        run: academic import publications.bib content/publication/ --compact
      - name: Create Pull Request
        # Set ID for `Check outputs` stage
        id: cpr
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          commit-message: 'content: import publications from Bibtex'
          title: Hugo Blox Builder - Import latest publications
          body: |
            Import the latest publications from `publications.bib` to `content/publication/`.
            将最新的出版物从`publications.bib`导入到`content/publication/`。
            [View Documentation](https://github.com/GetRD/academic-file-converter)
          base: main
          labels: automated-pr, content
          branch: hugoblox-import-publications
          delete-branch: true
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
