name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: HugoBlox/gh-action-updater@a781ff6f29558eeeec91efce7a92f9ee04a07f9c # v2.1.0
        with:
          feed-url: https://hugoblox.com/rss.xml
          readme-section: news
          branch: main
